### ISSUE TITLE
Knight movement across multiple dimensions

### ISSUE THREAD

**Issue by edave64** [opensofias/dimesweeper#2]
The current knight movement completely ignores the number of dimensions and the radius. To be consistent, we should come up with a way to expand that movement across dimensions above 2 and work with different radii.

The basis in 2D is that you can go on step in one direction, then two into another or the other way around.

First, lets imagine what happens when you increase the radius. To keep it so the knight can only make one movement per dimension (Which probably would be the easiest way to implement it), the length of these steps has to be increased. So when you have a radius 1, the pattern is (1,2) or (2,1), when the radius is 2 it would be (2,3) or (3,2).

Second, when you increase it to three dimensions, would it be (1,2,3), or (1,2,1)?

**Comment by edave64** [comment]
Also, are the possible movements in 3 dimensions (1,2,3) and (3,2,1), or (1,2,3), (3,2,1), (2,1,3) and (2,3,1)

**Comment by opensofias** [comment]
if we continue to use one-parameter neigborhoods, i would suggest he following:

radius 1: movement like a king, works in 1 dimension and higher..
in 3-d this would be (1,0,0), (0,1,0) (0,0,1)
radius 2: movement like a knight, works in 2 dimensions and higher:
(0,1,2), (1,0,2)... etc
radius 3: movement like a "superknight", one step in one dimension, two in another, three in yet another.

i haven't found a good way to implement this idea, tho..

**Comment by opensofias** [comment]
for reference, this general kind of movement is called "leaper", in fairy chess:
https://en.wikipedia.org/wiki/Fairy_chess_piece#Leapers

or hyper-fairy chess, in our case. ;)

**Comment by opensofias** [comment]
solved :)
